" No se pueden hacer strings multilinea \
tampoco asi "

/*
ERROR: LEXICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 1 | COLUMNA 1 | LITERAL MAL FORMADO: SE ESPERABA UN CIERRE DE CADENA, PERO SE ENCONTRO UN SALTO DE LINEA. |  

*/