/*
ERROR: LEXICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 5 | COLUMNA 1 | LITERAL MAL FORMADO: SE ESPERABA UN CIERRE DE CADENA, PERO SE ENCONTRO UN SALTO DE LINEA. |  
*/

"String sin cerrar