class Base: Base {
}


fn main() {
}
/* ERROR: SEMANTICO - DECLARACIONES
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 1 | COLUMNA 13 | HERENCIA CIRCULAR: LA CLASE Base HEREDA DE LA CLASE Base QUE HEREDA DIRECTA O INDIRECTAMENTE DE Base | */
