class Derivada {
}

fn main() {
	self = 12;
}/* ERROR: SEMANTICO - SENTENCIAS
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 5 | COLUMNA 2 | SE INTENTO ACCEDER A LA VARIABLE self PERO NO ESTA DEFINIDA EN EL AMBITO ACTUAL. | */
