fn main() {
	if (false) {
	} else {
		while(12*3) {
		}
	}
}
/* ERROR: SEMANTICO - SENTENCIAS
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 4 | COLUMNA 11 | SE ESPERABA UNA EXPRESION DE TIPO "Bool" PERO SE ENCONTRO UNA EXPRESION DE TIPO "I32" | */
