fn main() {
	if (true) {
		while(12) {
		}
	}
}
/* ERROR: SEMANTICO - SENTENCIAS
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 3 | COLUMNA 9 | SE ESPERABA UNA EXPRESION DE TIPO "Bool" PERO SE ENCONTRO UNA EXPRESION DE TIPO "I32" | */
