class Derivada : Base {
	create(I32: i) {}
	create(I32: i) {}
}


fn main() {
}
/* ERROR: SEMANTICO - DECLARACIONES
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 3 | COLUMNA 2 | SOLO SE PERMITE DECLARAR HASTA UN CONSTRUCTOR POR CLASE. | */
