fn main() {
	{I32: buenas;
	buenas = noches[1];}
}

/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 3 | TOKEN INESPERADO: SE ESPERABA UNA SENTENCIA O "}" Y SE ENCONTRO "I32" |*/