fn main() {}

class Hola {} 

/* ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 3 | COLUMNA 1 | TOKEN INESPERADO: SE ESPERABA TOKEN DE TIPO: EOF Y SE ENCONTRO "class" |
*/
