fn main() {
	1 + 2;
}

/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 2 | TOKEN INESPERADO: SE ESPERABA UNA DECLARACION DE VARIABLE, SENTENCIA O "}" Y SE ENCONTRO "1" |*/

