class Fn {
	create (: Hola) {}
}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 10 | TOKEN INESPERADO: SE ESPERABA UN IDENTIFICADOR DE CLASE O TIPO PRIMITIVO Y SE ENCONTRO ":" |*/
