class Hola {
	Array: hola;
} 

fn main () {}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 7 | TOKEN INESPERADO: SE ESPERABA Bool, I32, Str, Char Y SE ENCONTRO ":" |*/
