class Hola {
	Hola: Chau,
} 

fn main () {}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 8 | TOKEN INESPERADO: SE ESPERABA TOKEN DE TIPO: id Y SE ENCONTRO "Chau" |*/
