fn main() {
	a = 3;
	Hola: i;
}

/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 3 | COLUMNA 2 | TOKEN INESPERADO: SE ESPERABA UNA SENTENCIA O "}" Y SE ENCONTRO "Hola" |*/