

/* ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 0 | COLUMNA 0 | TOKEN INESPERADO: SE ESPERABA DECLARACION DE CLASES O METODO MAIN Y SE ENCONTRO "End Of File" |*/