class Fn {
	creater () {}
}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 2 | TOKEN INESPERADO: SE ESPERABA UN CONSTRUCTOR, METODO, ATRIBUTO O "}" Y SE ENCONTRO "creater" |*/ 
