fn main() {
	while (hola) else = 2;
}

/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 15 | TOKEN INESPERADO: SE ESPERABA UNA SENTENCIA Y SE ENCONTRO "else" |*/
