class Class {

}

fn main() {
	I32: buenas;
	buenas = 2 ** 3 + (2 / 4);
}

/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 7 | COLUMNA 14 | TOKEN INESPERADO: SE ESPERABA UNA EXPRESION Y SE ENCONTRO "*" |*/
