// Hola
class Hola {
	hola: hola
} 
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 3 | COLUMNA 2 | TOKEN INESPERADO: SE ESPERABA UN CONSTRUCTOR, METODO, ATRIBUTO O "}" Y SE ENCONTRO "hola" |*/
