class Hola {
	Array I32: hola,, hola;
} 

fn main () {}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 18 | TOKEN INESPERADO: SE ESPERABA TOKEN DE TIPO: id Y SE ENCONTRO "," |*/
