fn main() {
	(a.b.c.21.d);
}

/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 9 | TOKEN INESPERADO: SE ESPERABA UN IDENTIFICADOR DE METODO O VARIABLE Y SE ENCONTRO "21" |*/
