class Class {

}

fn main() {
	I32: buenas;
	buenas = buenas..getGreeting();
}


/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 7 | COLUMNA 18 | TOKEN INESPERADO: SE ESPERABA UN IDENTIFICADOR DE METODO O VARIABLE Y SE ENCONTRO "." |*/
