fn main() {
	if (hola) {} else ();
}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 21 | TOKEN INESPERADO: SE ESPERABA UNA EXPRESION Y SE ENCONTRO ")" |*/
