class Class {

}

fn main() {
	I32: buenas;
	buenas += 1;
}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 7 | COLUMNA 9 | TOKEN INESPERADO: SE ESPERABA = Y SE ENCONTRO "+" |*/
