fn main() {
(if (hola) r = 2);
}

/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 2 | TOKEN INESPERADO: SE ESPERABA UNA EXPRESION Y SE ENCONTRO "if" |*/
