class Fn {
	static fn coso ( Hola: h ): I32 {}
}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 28 | TOKEN INESPERADO: SE ESPERABA -> Y SE ENCONTRO ":" |*/
