class Fn {
	create (I32: cosa, I32: coso, Coso: cosas[1], ) {}
}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 43 | TOKEN INESPERADO: SE ESPERABA ) Y SE ENCONTRO "[" |*/
