class Fn {
	create (I32 Array: cosa) {}
}
/*ERROR: SINTACTICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 14 | TOKEN INESPERADO: SE ESPERABA : Y SE ENCONTRO "Array" |*/
