/*
ERROR: LEXICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 7 | COLUMNA 1 | LITERAL MAL FORMADO: SE ESPERABA UN CIERRE DE CADENA, PERO SE ENCONTRO UN SALTO DE LINEA. |  
*/

"Escape de cadena sin cerrar por EOF \