class Clase {
	fn metodo() -> I32 {
		return 9001110000;
	}
}

fn main() {
}
/* ERROR: LEXICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 3 | COLUMNA 10 | LITERAL MAL FORMADO: EL LITERAL NUMERICO EXCEDE EL RANGO DE LOS NUMEROS ENTEROS DE 32 BITS. | */
