3000111000

/*ERROR: LEXICO 
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 1 | COLUMNA 1 | LITERAL MAL FORMADO: EL LITERAL NUMERICO EXCEDE EL RANGO DE LOS NUMEROS ENTEROS DE 32 BITS. |  */