"String \n con nil \0 ups"


/*
ERROR: LEXICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 1 | COLUMNA 20 | LITERAL MAL FORMADO: SE ENCONTRO UN CARACTER INVALIDO NIL EN UNA CADENA |
*/

