"Un char no es multilinea"

'
a'

/*
ERROR: LEXICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 3 | COLUMNA 1 | LITERAL MAL FORMADO: EL LITERAL DEBE CONTENER EXACTAMENTE UN CARACTER |
*/