"un char deberia tener un solo char"
'ch'

/*
ERROR: LEXICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 2 | COLUMNA 1 | LITERAL MAL FORMADO: EL LITERAL DEBE CONTENER EXACTAMENTE UN CARACTER |
*/