/*
ERROR: LEXICO
| NUMERO DE LINEA: | NUMERO DE COLUMNA: | DESCRIPCION: |
| LINEA 7 | COLUMNA 1 | LITERAL MAL FORMADO: EL LITERAL DEBE CONTENER EXACTAMENTE UN CARACTER |
*/
"Escape de caracter sin cerrar por EOF"
'\